# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Zowe project.
title: Zowe
description: > # this means to ignore newlines until "keywords:"
  Zowe is an open source framework for leveraging data and applications in z/OS from modern applications and tools
keywords: mainframe, zos, open source, framework
theme: jekyll-theme-cayman
auto_ids: true

# URLs to various sites
latest_video_embed: https://www.youtube.com/embed/NX20ZMRoTtk
ibm_ztrial_url: https://www.openmainframeproject.org/projects/zowe/ztrial
github_repo_url: https://github.com/zowe
docs_site_url: https://docs.zowe.org
community_site_url: https://github.com/zowe/community/blob/master/README.md
forums_url: https://community.openmainframeproject.org/c/zowe
slack_url: https://slack.openmainframeproject.org
mailing_list_user_url: https://lists.openmainframeproject.org/g/zowe-user
youtube_zowe_url: https://www.youtube.com/playlist?list=PL8REpLGaY9QE_9d57tw3KQdwSVLKuTpUZ
conformance_page_url: https://www.openmainframeproject.org/projects/zowe/conformance
zos_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?version=
cli_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli&version=
cli_plugins_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli-plugins&version=
cli_active_development_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli-active-development&version=
smpe_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=smpe&version=
nightly_build_url: https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-release-local/org/zowe/nightly
zowe_build_slack_url: https://openmainframeproject.slack.com/archives/CC9QW5NJE
lts_url: https://github.com/zowe/zlc/blob/master/process/ReleaseProcess.md 
zowe_fmid: AZWE001
zowe_fmid_oss_version: 1.9.0
zos_component_install_doc_url: https://docs.zowe.org/stable/user-guide/install-zos.html
zowe_cli_install_doc_url: https://docs.zowe.org/stable/user-guide/cli-installcli.html
zowe_explorer_install_doc_url: https://docs.zowe.org/stable/user-guide/ze-install.html
vscode_marketplace_url: https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe


gems:
# Redirect plugin
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - dco_signoffs
  - .gitignore
